Repository akvo/akvo-rsr, pull requests merged in 2018-06, with the labels that each got.

#3201 [#3200] Support CSV format in the REST API
  akvo/rest/renderers.py
  akvo/settings/30-rsr.conf
  scripts/deployment/pip/requirements/2_rsr.txt
Labels: Feature request

#3218 [#3205] Fix subtle bug with user & enumerator permissions for None
  akvo/rsr/permissions.py
  akvo/rsr/tests/test_permissions.py
Labels: Bug

#3268 [#3267] Fix project editor save incorrectly detecting page changes
  akvo/rsr/static/scripts-src/project-editor.js
  akvo/rsr/static/scripts-src/project-editor.jsx
Labels: Bug

#3269 [#3265] Masquerade period dates in the public results view
  akvo/rsr/views/project.py
Labels: Bug

#3271 [#3270] Increase max-width for subtitle in my projects listing
  akvo/rsr/static/styles-src/main.css
  akvo/rsr/static/styles-src/main.scss
Labels: Bug

#3291 [#3289] directories: Fix incorrect pagination
  akvo/rest/views/project.py
  akvo/rsr/static/scripts-src/directory-utils.js
  akvo/rsr/static/scripts-src/directory-utils.jsx
Labels: Bug

#3189 [#3188] Fix default periods
  akvo/rest/views/project_editor.py
  akvo/rsr/management/commands/data_integrity.py
  akvo/rsr/management/commands/remove_period_dupes.py
  akvo/rsr/static/scripts-src/project-editor.js
  akvo/rsr/static/scripts-src/project-editor.jsx
  akvo/rsr/tests/rest/expected_responses.json
  akvo/rsr/tests/rest/test_project_editor.py
  akvo/rsr/views/my_rsr.py
Labels: Bug

#3290 [#3283] Initial cut of script to anonymize user information
  akvo/rsr/management/commands/anonymize_user.py
Labels: GDPR

#3297 [#3296] rest: Add a version api root view as docs
  akvo/rest/urls.py
Labels: Bug
