Repository akvo/akvo-rsr, pull requests merged in 2021-11, with the labels that each got.

#4683 [#4681] /rest/v1/project_update/ actually got slower with the cache
  .coveragerc
  akvo/cache/__init__.py
  akvo/cache/memcache.py
  akvo/cache/prepo.py
  akvo/cache/tests/__init__.py
  akvo/cache/tests/test_prepo.py
  akvo/rest/views/indicator_period_data.py
  akvo/rest/views/partnership.py
  akvo/rest/views/project.py
  akvo/rest/views/project_update.py
  akvo/rest/viewsets.py
  akvo/settings/20-default.conf
Labels: Priority: High

#4688 Fix #4671: Deprecation(django): Replace base_name by basename in urls.py
  akvo/rest/urls.py
  scripts/docker/ci/build.sh
Labels: Priority: Medium

#4697 [#4682]: Passing a malformed filter to REST endpoints silently fails and returns unfiltered results
  akvo/rest/filters.py
  akvo/rest/tests/__init__.py
  akvo/rest/tests/test_filters.py
Labels: Bug, Priority: Medium

#4695 [#4668]: Speed up django unit tests
  README.dev.md
  akvo/rsr/tests/models/test_custom_field.py
  akvo/rsr/tests/models/test_project.py
  akvo/rsr/tests/models/test_results_aggregation.py
  scripts/docker/ci/build.sh
Labels: Priority: Low

#4696 Fix #4684: CI: Use makemigrations --check
  scripts/docker/ci/build.sh
Labels: Priority: Low

#4705 [#4700] Fix indicators at enumerator & admin view
  akvo/rsr/spa/app/components/IndicatorItem.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx
  akvo/rsr/spa/app/modules/results/enumerator.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
Labels: Bug, Type: UX Required
