Repository akvo/akvo-rsr, pull requests merged in 2021-12, with the labels that each got.

#4713 [#4712] Fix newly assigned and pre-approved indicator
  akvo/rsr/spa/app/components/IndicatorItem.jsx
  akvo/rsr/spa/app/components/ScoringField.jsx
  akvo/rsr/spa/app/modules/enumerators/enumerators.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx
  akvo/rsr/spa/app/modules/results/enumerator.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
  akvo/rsr/spa/app/modules/results/filters.js
  akvo/rsr/spa/app/modules/results/filters.test.js
  akvo/rsr/spa/app/modules/results/pending-approval.jsx
Labels: Bug

#4715 [#4714] Make reimport step optional when change project parent
  akvo/rsr/management/commands/change_project_parent.py
  akvo/rsr/management/commands/nuffic_hierarchy_changes.py
  akvo/rsr/usecases/change_project_parent.py
Labels: Chore

#4735 Add command clear_all_sessions
  akvo/rsr/management/commands/clear_all_sessions.py
  akvo/rsr/spa/app/main.js
Labels: Chore

#4736 Flush session store as well when clearing sessions
  akvo/rsr/management/commands/clear_all_sessions.py
Labels: Chore

#4746 [#4743] fix: my_projects endpoint filtering by country
  akvo/rest/views/project.py
  akvo/rsr/tests/rest/test_my_projects.py
Labels: Bug

#4756 [#4745] Fix can't delete main photo at project updates
  akvo/rsr/spa/app/modules/updates/updates.jsx
Labels: Bug

#4737 [#4541] Remove results admin featflag except nuffic
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
Labels: MyRSR refactor

#4753 Upgrade urllib3>=1.26.5
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
Labels: Chore, dependencies, python

#4752 Upgrade to Django>=3.2.10
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/production.in
Labels: Chore, dependencies, python

#4762 [#4761] Fix: invalid space when searching project by title
  akvo/rsr/spa/app/modules/projects/projects.jsx
Labels: Bug, Quick Fix

#4742 [#4738] chore: enable coverage on most paths
  .coveragerc
  .gitignore
  .semaphore/semaphore.yml
  README.dev.md
  README.md
  ci/build-semaphoreci.sh
  docker-compose.ci.yaml
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/dev.in
  scripts/devhelpers/coverage.sh
  scripts/docker/ci/build.sh
Labels: Chore

#4751 [#4582] Feat: MnE edit, delete function at pending approval tab
  akvo/rsr/spa/app/components/ScoringField.jsx
  akvo/rsr/spa/app/images/edit-button.svg
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/components/Disaggregations.jsx
  akvo/rsr/spa/app/modules/results-admin/components/QualitativeIndicator.jsx
  akvo/rsr/spa/app/modules/results-admin/components/QuantitativeIndicator.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results-admin/components/StatusBadge.jsx
  akvo/rsr/spa/app/modules/results-admin/components/index.js
Labels: In Progress, MyRSR refactor
