Repository akvo/akvo-rsr, pull requests merged in 2022-07, with the labels that each got.

#5024 [#5022] Replace get_absolute_url with cacheable_url and cached_proprty in serializers and models
  akvo/rest/serializers/rsr_serializer.py
  akvo/rsr/models/focus_area.py
  akvo/rsr/models/organisation.py
  akvo/rsr/models/project.py
  akvo/rsr/models/project_update.py
  akvo/rsr/models/user.py
Labels: Type: Performance, Type: Results framework

#5026 [#5025] Fix wrong org by replacing it with the number of indicators
  akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx
  akvo/rsr/spa/app/modules/announcements/announcement.jsx
  akvo/rsr/spa/app/modules/enumerators/assignment-view.jsx
  akvo/rsr/spa/app/styles/main.scss
Labels: Bug, Quick Fix, Needs Review

#5039 [#5038] Fix enumerators can edit project updates they do not own
  akvo/rsr/models/__init__.py
  akvo/rsr/project_role_auth.py
  akvo/rsr/tests/rest/test_permissions.py
  akvo/rsr/tests/rest/test_project_update.py
  akvo/rsr/tests/test_permissions.py
Labels: Bug

#5040 [#5033] Improve the UI for qualitative indictor update
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss
Labels: Feature request, Type: Layout/Design

#5043 [#5033] Add more space in update section & show description
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
Labels: Quick Fix, Needs Review, Type: Layout/Design

#5015 [#5008] Create schedule demo form
  akvo/rsr/dir/app/modules/components/RsrButton.jsx
  akvo/rsr/dir/app/modules/main/index.jsx
  akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx
  akvo/rsr/dir/app/modules/schedule-demo/ScheduleDemo.jsx
  akvo/rsr/dir/app/modules/schedule-demo/index.js
  akvo/rsr/dir/app/root.jsx
  akvo/rsr/dir/app/styles/app.scss
  akvo/rsr/dir/app/styles/buttons.scss
  akvo/rsr/dir/app/styles/schedule-demo.scss
  akvo/rsr/dir/app/utils/config.js
  akvo/rsr/dir/package-lock.json
  akvo/rsr/dir/package.json
Labels: Feature request, Needs Review

#5021 [#5020] Fix broken image at detail project update
  akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx
Labels: Bug, Quick Fix, Type: Layout/Design

#5047 More devScripts
  .dockerignore
  ci/training-envs/.gitignore
  ci/training-envs/README.md
  scripts/devhelpers/dc-reset.sh
  scripts/devhelpers/dc-resetWithDump.sh
  scripts/devhelpers/dc-resetWithNewDump.sh
Labels: Chore
