Repository akvo/akvo-rsr, pull requests merged in 2022-06, with the labels that each got.

#4974 [#4764] Fix sorting by activeness and semi-doughnut chart
  akvo/rsr/dir/app/images/home-monitoring.svg
  akvo/rsr/dir/app/modules/components/chart/Bar.jsx
  akvo/rsr/dir/app/modules/components/chart/Dot.jsx
  akvo/rsr/dir/app/modules/components/chart/LabelsXAxis.jsx
  akvo/rsr/dir/app/modules/components/chart/LabelsYAxis.jsx
  akvo/rsr/dir/app/modules/main/components/MapView.jsx
  akvo/rsr/dir/app/modules/main/queries.js
  akvo/rsr/dir/app/modules/main/sections/FooterSection.jsx
  akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx
  akvo/rsr/dir/app/modules/main/sections/ProjectSection.jsx
  akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx
  akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx
  akvo/rsr/dir/app/modules/project-page/components/SemiDoughnut.jsx
  akvo/rsr/dir/app/modules/project-page/views/Home.jsx
  akvo/rsr/dir/app/modules/project-page/views/ResultOverview.jsx
  akvo/rsr/dir/app/modules/wcaro-index/view.scss
  akvo/rsr/dir/app/styles/app.scss
  akvo/rsr/dir/app/styles/home-page.scss
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/misc.js
Labels: Needs Review, MyRSR refactor, Type: Layout/Design

#4979 [#4764] Fix the first illustration not mirrored on safari
  akvo/rsr/dir/app/images/home-monitoring.svg
  akvo/rsr/dir/app/styles/app.scss
  akvo/rsr/dir/app/styles/home-page.scss
Labels: Type: Layout/Design

#4980 [#4978] Remove Dutch foreign ministry org
  akvo/rsr/management/commands/remote_netherlands_foreign_ministry.py
Labels: Chore

#4985 Fix #4984: speed up projects_by_id endpoint
  akvo/rest/serializers/project.py
  akvo/rest/views/project.py
  akvo/rsr/management/commands/update_project_thumbnails.py
  akvo/rsr/migrations/0218_project_thumbnail_cache.py
  akvo/rsr/models/__init__.py
  akvo/rsr/models/project.py
  akvo/rsr/models/project_thumbnail.py
  akvo/rsr/tests/models/test_project_thumbnail.py
  akvo/settings/30-rsr.conf
Labels: Bug

#4989 [#4242] Added new announcement: 07-05-2022
  akvo/rsr/spa/app/modules/announcements/17-05-2022.jsx
  akvo/rsr/spa/app/modules/announcements/list.js
  akvo/rsr/spa/app/modules/enumerators/enumerators.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx
  akvo/rsr/spa/app/modules/results/router.jsx
Labels: Needs Review, RSR Updates, Project reports

#4993 [#4992] Fix old Results UI still there for Nuffic
  akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/modules/projects/conditional-link.jsx
  akvo/rsr/spa/app/modules/projects/table-view.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
Labels: Bug, Needs Review, Nuffic

#4995 [#4242] Change released date from 17 to 27 May 2022
  akvo/rsr/spa/app/modules/announcements/27-05-2022.jsx
  akvo/rsr/spa/app/modules/announcements/list.js
Labels: Quick Fix, Needs Review

#4998 [#4996] Fix selected className at old ui filtering not working
  akvo/rsr/dir/app/modules/index/filter-bar.jsx
Labels: Bug, Quick Fix

#5001 [#5000] Fix no active field on revised update for enumerator form link
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
Labels: Bug, Quick Fix, Needs Review

#5007 4987 fix project updates and org name
  akvo/rsr/dir/app/json/features.json
  akvo/rsr/dir/app/json/how-it-works.json
  akvo/rsr/dir/app/modules/index/map.jsx
  akvo/rsr/dir/app/modules/main/components/MapView.jsx
  akvo/rsr/dir/app/modules/main/index.jsx
  akvo/rsr/dir/app/modules/main/sections/ContactForm.jsx
  akvo/rsr/dir/app/modules/main/sections/FooterSection.jsx
  akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx
  akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx
  akvo/rsr/dir/app/modules/project-page/components/Author.jsx
  akvo/rsr/dir/app/modules/project-page/views/Home.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx
  akvo/rsr/dir/app/styles/app.scss
  akvo/rsr/dir/app/styles/home-page.scss
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/config.js
  akvo/rsr/dir/app/utils/string.js
Labels: Needs Review, Priority: High, Type: Layout/Design

#5006 #5004: Fix: Disallow saving a project during deletion
  akvo/rsr/models/project.py
  akvo/rsr/tests/models/test_project.py
Labels: Bug

#5009 [#5003] Fix mobile view of enumerator forms
  akvo/rsr/spa/app/modules/projects/projects.jsx
  akvo/rsr/spa/app/modules/projects/styles.scss
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.scss
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
  akvo/rsr/spa/app/modules/results/styles.scss
  akvo/rsr/spa/app/modules/updates/styles.scss
  akvo/rsr/spa/app/styles/container.scss
Labels: Bug, Needs Review, Type: Layout/Design

#5011 [#5010] Fix enumerators tab not available for admin role
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/utils/feat-flags.js
Labels: Bug, Quick Fix

#5018 [#5017] Speed up Results framework endpoint
  akvo/rest/serializers/indicator.py
  akvo/rest/serializers/indicator_period.py
  akvo/rest/serializers/indicator_period_data.py
  akvo/rest/serializers/result.py
  akvo/rest/views/result.py
Labels: Bug

#5014 [#4991] Create support links floating button
  akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx
  akvo/rsr/spa/app/modules/announcements/announcement.jsx
  akvo/rsr/spa/app/modules/announcements/help-links.json
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/styles/main.scss
Labels: Feature request, Needs Review, Type: Layout/Design
