Repository akvo/akvo-rsr, pull requests merged in 2022-09, with the labels that each got.

#5099 [#5096] iati export does not update checks after project is updated
  akvo/iati/exports/iati_export.py
  akvo/iati/exports/iati_org_export.py
  akvo/rsr/management/commands/perform_iati_checks.py
  akvo/rsr/tests/usecases/test_run_iati_validation_jobs.py
  akvo/rsr/usecases/iati_validation/__init__.py
  akvo/rsr/usecases/iati_validation/iati_validation_job_runner.py
  akvo/rsr/usecases/iati_validation/run_validation_jobs.py
  akvo/rsr/usecases/iati_validation/schedule_validation.py
Labels: Bug

#5098 [#5095] Fix transaction redirect does not load values
  akvo/rsr/spa/app/modules/editor/section6/section6.jsx
Labels: Bug, Type: Project editor

#5101 [#5100] Fix Project update video link issue
  akvo/rsr/dir/app/index.html
  akvo/rsr/dir/app/modules/project-page/components/Video.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/string.js
Labels: Bug, Type: Layout/Design, javascript

#5102 [#5100] Create thumbnail component
  akvo/rsr/dir/app/modules/components/YoutubeThumb.jsx
  akvo/rsr/dir/app/modules/project-page/components/Author.jsx
  akvo/rsr/dir/app/modules/project-page/components/Thumbnail.jsx
  akvo/rsr/dir/app/modules/project-page/components/Video.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/config.js
  akvo/rsr/dir/app/utils/string.js
  akvo/rsr/spa/app/components/Thumbnail.jsx
  akvo/rsr/spa/app/modules/updates/updates.jsx
Labels: Feature request, Type: Layout/Design

#5103 5100 youtube thumb in highlight
  akvo/rsr/dir/app/modules/index/view.jsx
  akvo/rsr/dir/app/modules/project-page/views/Home.jsx
  akvo/rsr/dir/app/styles/main.scss
  akvo/rsr/dir/app/styles/project-page.scss
Labels: Quick Fix, Type: Layout/Design, javascript

#5092 Update tools for training env deployment
  ci/training-envs/Dockerfile
  ci/training-envs/README.md
  ci/training-envs/docker-compose.yml
  scripts/data/make-and-restore-production-dump.sh
Labels: Chore

#5111 [#4910] Fix invalid selected card and add a new contributing project func. in the project view
  akvo/rsr/dir/app/modules/project-page/views/Results.jsx
  akvo/rsr/spa/app/modules/hierarchy/column.jsx
  akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
  akvo/rsr/spa/app/modules/hierarchy/styles.scss
  akvo/rsr/spa/app/modules/program/indicator.jsx
Labels: Bug, Type: Layout/Design

#5113 [#4910] Fix project card not clickable in the hierarchy tab
  akvo/rsr/spa/app/modules/hierarchy/card.jsx
  akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
Labels: Bug

#5115 [#5114] Fix import results set option not available in the editor
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
  akvo/rsr/spa/app/modules/editor/section5/section5.jsx
Labels: Bug, Type: Project editor

#5119 Prefer deploying RSR training envs on specific nodes
  ci/training-envs/templates/deployment.yaml
  ci/training-envs/values.yaml
Labels: Chore

#5121 [#5073] Fix Project editor - description section not loading
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
Labels: Bug, Quick Fix, Type: Project editor

#5123 [#5048] Fix project filtering not showing on partner sites
  akvo/rsr/dir/app/global-style.js
  akvo/rsr/dir/app/modules/home/Home.jsx
Labels: Bug, Type: Layout/Design

#5124 Use production branch
  README.md
  ci/deploy-semaphoreci.sh
  ci/promote-test-to-prod.sh
  doc/deploying.md
Labels: Chore

#5125 [#5048] Fix project page invalid multiple images
  akvo/rsr/dir/app/modules/project-page/components/Thumbnail.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx
  akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/misc.js
Labels: Bug, Type: Layout/Design
