Repository akvo/akvo-rsr, pull requests merged in 2022-12, with the labels that each got.

#5179 [#5161] Fix whitescreen when attempting a negative value for dsg
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/utils/final-field.jsx
Labels: Bug, javascript, For Production, A4A

#5172 [#5169] Block switching indicators to cumulative reporting
  akvo/rest/serializers/indicator.py
  akvo/rest/urls.py
  akvo/rest/views/__init__.py
  akvo/rest/views/indicator.py
  akvo/rsr/models/result/indicator.py
  akvo/rsr/spa/app/modules/editor/action-types.js
  akvo/rsr/spa/app/modules/editor/actions.js
  akvo/rsr/spa/app/modules/editor/reducer.js
  akvo/rsr/spa/app/modules/editor/section5/cumulative/BlockToggleApi.jsx
  akvo/rsr/spa/app/modules/editor/section5/cumulative/Toggle.jsx
  akvo/rsr/spa/app/modules/editor/section5/cumulative/index.js
  akvo/rsr/spa/app/modules/editor/section5/indicators.jsx
  akvo/rsr/tests/rest/test_indicator.py
  akvo/rsr/tests/usecases/test_indicator_update_contribution_count.py
  akvo/rsr/usecases/indicator_contribution.py
Labels: A4A

#5174 Newer UI for cumulative updates hint
  akvo/rsr/spa/app/components/AuditTrail.jsx
  akvo/rsr/spa/app/components/ExpandIcon.jsx
  akvo/rsr/spa/app/components/UpdatesHint.jsx
  akvo/rsr/spa/app/components/UpdatesHint.scss
  akvo/rsr/spa/app/components/UpdatesHistory.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.scss
  akvo/rsr/spa/app/modules/results-admin/components/DisaggregationsInput.jsx
  akvo/rsr/spa/app/modules/results-admin/components/QualitativeIndicator.jsx
  akvo/rsr/spa/app/modules/results-admin/components/QuantitativeIndicator.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.scss
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss
  akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
  akvo/rsr/spa/app/modules/results/reducer.js
  akvo/rsr/spa/app/styles/main.scss
  akvo/rsr/spa/app/styles/vars.scss
  akvo/rsr/spa/app/utils/constants.js
  akvo/rsr/spa/app/utils/final-field.jsx
  akvo/rsr/spa/app/utils/misc.js
  akvo/rsr/spa/app/utils/string.js
Labels: A4A

#5128 Improve project hierarchies frontend view
  akvo/rest/serializers/__init__.py
  akvo/rest/serializers/project.py
  akvo/rest/urls.py
  akvo/rest/views/__init__.py
  akvo/rest/views/program.py
  akvo/rest/views/project.py
  akvo/rest/viewsets.py
  akvo/rsr/spa/app/modules/hierarchy/column.jsx
  akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
  akvo/rsr/spa/app/modules/hierarchy/services.js
  akvo/rsr/spa/app/modules/hierarchy/styles.scss
  akvo/rsr/spa/app/utils/misc.js
  akvo/rsr/tests/rest/test_project_hierarchy.py
Labels: Feature request, Type: Performance
