Repository akvo/akvo-rsr, pull requests merged in 2022-02, with the labels that each got.

#4813 [#4803] Add title indicator at results overview
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results/styles.scss
Labels: Needs Review

#4812 [#4802] Move description and period at results admin
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
Labels: Needs Review

#4794 [#4788] create an initial program in dev env
  akvo/rsr/management/commands/populate_local_db.py
  akvo/rsr/tests/base.py
Labels: Bug, Chore, Priority: Low, python

#4807 [#4806] Fix: delayed location changes by adding loading indicator
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
  akvo/rsr/spa/app/modules/editor/section7/section7.jsx
Labels: Bug, Needs Review, Priority: High

#4816 [#4808]: Let a4a_optimy_import leave publishingstatus alone
  akvo/rsr/management/commands/a4a_optimy_import.py
Labels: Feature request

#4818 [#4809] Set default validation set for a4a_optimy_import
  akvo/rsr/management/commands/a4a_optimy_import.py
Labels: Feature request

#4821 [#4814] Fix upload document at section 9
  akvo/rsr/spa/app/modules/editor/section9/docs/uploader.jsx
Labels: Needs Review

#4825 [#4824] Deleting parent period deletes child periods
  akvo/rsr/migrations/0217_cascade_indicator_period_deletes.py
  akvo/rsr/models/result/indicator_period.py
  akvo/rsr/tests/models/test_indicator_period.py
Labels: Bug

#4829 [#4823] Fix project editor permissions at project view
  akvo/rsr/spa/app/modules/editor/actions.js
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
Labels: Bug

#4831 [#4754] Fix sometimes get an error when deleting periods
  akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx
  akvo/rsr/spa/app/utils/auto-save.jsx
Labels: Bug, Needs Review, Priority: High

#4815 [#4811] Fix: Creating orgs with logos on google cloud
  akvo/rsr/signals.py
  akvo/utils.py
Labels: Bug, Priority: Low

#4835 [#4833] Clean up orphaned indicator periods
  akvo/rsr/management/commands/cleanup_indicator_periods.py
  akvo/rsr/tests/commands/test_cleanup_indicator_periods.py
  akvo/rsr/tests/utils.py
Labels: Chore

#4838 Chore: Code cleanup
  akvo/rsr/management/commands/nuffic_hierarchy_changes.py
  scripts/devhelpers/populate-db.sh
  scripts/devhelpers/restart-webpack
Labels: Chore

#4839 [#4837] Fix bug 'contributed to' field not saved
  akvo/rsr/spa/app/modules/editor/actions.js
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
  akvo/rsr/spa/app/modules/editor/reducer.js
  akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx
  akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx
  akvo/rsr/spa/app/modules/editor/section1/section1.jsx
Labels: Bug, Needs Review

#4850 [#4849] Log when Project location is being deleted from a project
  akvo/rsr/models/location.py
Labels: Bug, Chore

#4845 [#4828] Fix Misplaced chart visual in the 'Description' section
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss
  akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx
  akvo/rsr/spa/app/utils/target-charts.jsx
Labels: Bug

#4855 [#4853] Fix percentage indicator update at TobeReport
  akvo/rsr/spa/app/modules/editor/section5/section5.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/update.jsx
Labels: Bug

#4863 [#4860] Fix invalid disaggregation at program overview
  akvo/rsr/spa/app/modules/program/ApprovedUpdates.jsx
  akvo/rsr/spa/app/modules/program/Comments.jsx
  akvo/rsr/spa/app/modules/program/Disaggregations.jsx
  akvo/rsr/spa/app/modules/program/ExpandIcon.jsx
  akvo/rsr/spa/app/modules/program/ProgramPeriod.jsx
  akvo/rsr/spa/app/modules/program/ProjectSummary.jsx
  akvo/rsr/spa/app/modules/program/config.js
  akvo/rsr/spa/app/modules/program/indicator.jsx
  akvo/rsr/spa/app/modules/program/program.jsx
  akvo/rsr/spa/app/modules/program/result.jsx
Labels: Bug

#4865 [#4853] Hide approved update at tobe reported view
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss
  akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx
  akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/update.jsx
Labels: Bug

#4869 [#4856] part 2: fix: restore DB dump in training env as postgres user
  ci/training-envs/templates/seedDatabase.yaml
Labels: Bug
