Repository akvo/akvo-rsr, pull requests merged in 2022-08, with the labels that each got.

#5056 [#5051] Show review note if status is R in Audit trail
  akvo/rsr/spa/app/components/AuditTrail.jsx
Labels: Quick Fix, Needs Review

#5058 [#5057] Add redux persist to store important user props
  akvo/rsr/spa/app/main.js
  akvo/rsr/spa/app/modules/editor/editor.jsx
  akvo/rsr/spa/app/store/config.js
  akvo/rsr/spa/app/store/root-reducer.js
  akvo/rsr/spa/app/store/user-reducer.js
  akvo/rsr/spa/app/top-bar.jsx
  akvo/rsr/spa/package-lock.json
  akvo/rsr/spa/package.json
Labels: Bug, Needs Review

#5063 [#5057] Fix persistence editor caused date invalid
  akvo/rsr/spa/app/modules/editor/editor.jsx
  akvo/rsr/spa/app/store/root-reducer.js
Labels: Bug, Quick Fix

#5064 [#5057] Create results reducer to reduce reloading page
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx
  akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx
  akvo/rsr/spa/app/modules/results-overview/components/index.js
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/action-types.js
  akvo/rsr/spa/app/modules/results/actions.js
  akvo/rsr/spa/app/modules/results/reducer.js
  akvo/rsr/spa/app/modules/results/router.jsx
  akvo/rsr/spa/app/modules/results/update.jsx
  akvo/rsr/spa/app/store/config.js
  akvo/rsr/spa/app/store/root-reducer.js
  akvo/rsr/spa/app/utils/misc.js
Labels: Needs Review, Type: Results framework, MyRSR refactor, javascript

#5072 devops: place rsr on its own node
  ci/k8s/deployment.yml
Labels: Priority: High, k8s

#5074 [#5073] Fix editor long delays before loading
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
Labels: Bug, Quick Fix, Type: Project editor

#5070 [#5061] fix project.created at is naive datetime when saving a project
  akvo/iati/imports/__init__.py
  akvo/rsr/management/commands/cleanup_untitled_and_unpublished_projects.py
  akvo/rsr/management/commands/delete_empty_projects.py
  akvo/rsr/management/commands/expire_all_sessions.py
  akvo/rsr/migrations/0047_auto_20160115_1039.py
  akvo/rsr/migrations/0220_project_naive_created_at.py
  akvo/rsr/models/iati_activity_import.py
  akvo/rsr/models/iati_import.py
  akvo/rsr/models/iati_import_job.py
  akvo/rsr/models/project.py
  akvo/rsr/signals.py
  akvo/rsr/tests/base.py
  akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py
  akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py
  akvo/rsr/views/py_reports/organisation_projects_overview_report.py
  akvo/rsr/views/py_reports/results_indicators_excel_report.py
  akvo/utils/__init__.py
  akvo/utils/datetime.py
Labels: Chore

#5082 [#5081] Fix disaggregation in public project overview
  akvo/rsr/dir/app/features/collapse/collapseSlice.js
  akvo/rsr/dir/app/features/periods/filterSlice.js
  akvo/rsr/dir/app/features/periods/periodSlice.js
  akvo/rsr/dir/app/features/results/resultSlice.js
  akvo/rsr/dir/app/main.js
  akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx
  akvo/rsr/dir/app/modules/project-page/components/Disaggregations.jsx
  akvo/rsr/dir/app/modules/project-page/components/ExpandIcon.jsx
  akvo/rsr/dir/app/modules/project-page/components/Indicator/Indicator.jsx
  akvo/rsr/dir/app/modules/project-page/components/Indicator/PanelHeader.jsx
  akvo/rsr/dir/app/modules/project-page/components/Indicator/Qualitative.jsx
  akvo/rsr/dir/app/modules/project-page/components/Indicator/Quantitative.jsx
  akvo/rsr/dir/app/modules/project-page/components/Indicator/index.js
  akvo/rsr/dir/app/modules/project-page/components/PeriodApi.jsx
  akvo/rsr/dir/app/modules/project-page/components/PopPeriods.jsx
  akvo/rsr/dir/app/modules/project-page/components/UpdateApi.jsx
  akvo/rsr/dir/app/modules/project-page/queries.js
  akvo/rsr/dir/app/modules/project-page/views/Home.jsx
  akvo/rsr/dir/app/modules/project-page/views/ResultItem.jsx
  akvo/rsr/dir/app/modules/project-page/views/ResultOverview.jsx
  akvo/rsr/dir/app/modules/project-page/views/Results.jsx
  akvo/rsr/dir/app/modules/project-page/views/Updates.jsx
  akvo/rsr/dir/app/store.js
  akvo/rsr/dir/app/styles/project-page.scss
  akvo/rsr/dir/app/utils/misc.js
  akvo/rsr/dir/package-lock.json
  akvo/rsr/dir/package.json
Labels: Bug, Priority: High, javascript

#5089 [#5087] Add optional chaining at results reducer state
  akvo/rsr/spa/app/modules/results/router.jsx
Labels: Bug, Quick Fix

#5090 Fix bug project editor sections are loaded only once
  akvo/rsr/spa/app/modules/editor/project-init-handler.js
Labels: Bug, Type: Project editor, Priority: High
