Repository akvo/akvo-rsr, pull requests merged in 2022-05, with the labels that each got.

#4948 [#4947] IATI export datetime using correct format
  akvo/iati/exports/iati_export.py
  akvo/iati/exports/iati_org_export.py
  akvo/iati/exports/utils.py
  akvo/rsr/tests/iati_export/__init__.py
  akvo/rsr/tests/iati_export/test_iati_export.py
  akvo/rsr/tests/iati_export/test_iati_org_export.py
  akvo/settings/20-default.conf
Labels: Bug

#4959 [#4957] Hidden back button at the enumerator preview/jwt page
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/root.jsx
Labels: Bug

#4964 [#4939] Remove IATI import feature
  akvo/iati/imports/__init__.py
  akvo/iati/imports/mappers/Cordaid/__init__.py
  akvo/iati/imports/mappers/Cordaid/financials.py
  akvo/iati/imports/mappers/Cordaid/partnerships.py
  akvo/iati/imports/mappers/CordaidZip/__init__.py
  akvo/iati/imports/mappers/CordaidZip/financials.py
  akvo/iati/imports/mappers/CordaidZip/links.py
  akvo/iati/imports/mappers/CordaidZip/organisations.py
  akvo/iati/imports/mappers/CordaidZip/partnerships.py
  akvo/iati/imports/mappers/ICCO/__init__.py
  akvo/iati/imports/mappers/ICCO/descriptions.py
  akvo/iati/imports/mappers/Result_only/__init__.py
  akvo/iati/imports/mappers/__init__.py
  akvo/iati/imports/mappers/classifications.py
  akvo/iati/imports/mappers/contacts.py
  akvo/iati/imports/mappers/dates.py
  akvo/iati/imports/mappers/defaults.py
  akvo/iati/imports/mappers/descriptions.py
  akvo/iati/imports/mappers/financials.py
  akvo/iati/imports/mappers/humanitarian.py
  akvo/iati/imports/mappers/links.py
  akvo/iati/imports/mappers/locations.py
  akvo/iati/imports/mappers/partnerships.py
  akvo/iati/imports/mappers/related_projects.py
  akvo/iati/imports/mappers/results.py
  akvo/iati/imports/mappers/special_reporting.py
  akvo/rsr/admin.py
  akvo/rsr/management/commands/cleanup_untitled_and_unpublished_projects.py
  akvo/rsr/management/commands/iati_import.py
  akvo/rsr/management/commands/user_cleanup.py
  akvo/rsr/migrations/0032_auto_20151001_0956.py
  akvo/rsr/migrations/0047_auto_20160115_1039.py
  akvo/rsr/migrations/0219_rm_iati_import.py
  akvo/rsr/models/__init__.py
  akvo/rsr/models/iati_activity_import.py
  akvo/rsr/models/iati_import.py
  akvo/rsr/models/iati_import_job.py
  akvo/rsr/models/iati_import_log.py
  akvo/rsr/models/project.py
  akvo/rsr/tests/commands/test_cleanup_untitled_and_unpublished_projects.py
  akvo/rsr/tests/iati_import/__init__.py
  akvo/rsr/tests/iati_import/test_iati_import.py
  akvo/rsr/tests/iati_import/xml_files.py
  akvo/settings/90-finish.conf
  akvo/templates/iati_import/import_done_message.html
  akvo/templates/iati_import/import_done_message.txt
  akvo/templates/iati_import/import_done_subject.txt
Labels: Chore

#4973 [#4764] Remove beta button at results view
  akvo/rsr/dir/app/modules/main/index.jsx
  akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx
  akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx
  akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx
  akvo/rsr/dir/app/styles/app.scss
  akvo/rsr/dir/app/styles/home-page.scss
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
Labels: Needs Review, MyRSR refactor

#4976 [#4975] Remove iati_import cronjob
  akvo/settings/90-finish.conf
Labels: Bug
