Repository akvo/akvo-rsr, pull requests merged in 2022-03, with the labels that each got.

#4873 [#4872] fix opening project results using copied form access link
  akvo/rest/authentication.py
  akvo/rest/views/indicator_period.py
  akvo/rest/views/indicator_period_data.py
  akvo/rest/views/program_results_geo.py
  akvo/rest/views/project.py
  akvo/rest/views/project_editor.py
  akvo/rest/views/project_enumerators.py
  akvo/rest/views/project_overview.py
  akvo/rest/views/project_update.py
  akvo/rest/views/result.py
  akvo/rest/views/user.py
  akvo/rest/viewsets.py
  akvo/rsr/models/__init__.py
  akvo/rsr/tests/rest/test_authentication.py
Labels: Bug

#4878 [#4874] Fix: Database imported from production with superuser is read-only
  ci/training-envs/templates/seedDatabase.yaml
  scripts/data/restore-from-dump.sh
Labels: Bug

#4836 [#4822] extend data integrity command to include results with parents belonging to multiple projects
  akvo/rsr/checks/__init__.py
  akvo/rsr/checks/indicators.py
  akvo/rsr/checks/periods.py
  akvo/rsr/checks/results.py
  akvo/rsr/management/commands/data_integrity.py
  akvo/rsr/management/commands/helpers/__init__.py
  akvo/rsr/management/commands/helpers/data_integrity.py
Labels: Feature request

#4881 [#4880] Run Google Cloud Profiler in GCP
  akvo/rsr/tests/rsr_utils/test_utils.py
  akvo/utils.py
  akvo/wsgi.py
  ci/build-semaphoreci.sh
  ci/k8s/config-prod.yml
  ci/k8s/config-test.yml
  ci/k8s/deployment.yml
  ci/training-envs/templates/deployment.yaml
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/production.in
Labels: Chore

#4886 [#4880] Use string instead of boolean in configmap
  ci/k8s/config-prod.yml
  ci/k8s/config-test.yml
Labels: Bug, Chore

#4890 [#4888] Fix bug permissions for the User role
  akvo/rest/views/project.py
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
  akvo/rsr/spa/app/modules/results/filter-checkbox.jsx
  akvo/rsr/spa/app/modules/results/router.jsx
  akvo/rsr/tests/rest/test_project_access.py
Labels: Bug

#4893 [#4892] Fix bug:Unable to select a city when adding a new organization
  akvo/rsr/spa/app/modules/editor/section7/location-items/search-item.jsx
Labels: Bug, Needs Review

#4891 [#4889] Fix bug: Enumerators can see unassigned indicators
  akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
Labels: Bug, Needs Review

#4899 [#4898] Fix bug: Results Indicator dates on audit trail
  akvo/rsr/spa/app/components/AddUpdate.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx
  akvo/rsr/spa/app/modules/results/enumerator.jsx
  akvo/rsr/spa/app/modules/results/period.jsx
Labels: Bug, Needs Review

#4903 [#4900]: fix pip-compile
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
Labels: Bug, Chore

#4915 [#4914] Fix bug description field at project editor
  akvo/rsr/spa/app/modules/editor/reducer.js
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
Labels: Bug, Needs Review
