Repository akvo/akvo-rsr, pull requests merged in 2022-01, with the labels that each got.

#4763 [#4582] Refactoring UI To be Reported and edit, delete reintroduced
  akvo/rsr/spa/app/components/Highlighted.jsx
  akvo/rsr/spa/app/modules/enumerators/enumerators.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.scss
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/components/index.js
Labels: In Progress, MyRSR refactor

#4770 [#4769] Fix Local CI execution
  ci/build-semaphoreci.sh
Labels: Bug, Chore

#4773 [#4582] Refactoring UI Enumerator view and edit, del reintroduced
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
  akvo/rsr/spa/app/modules/results/router.jsx
Labels: MyRSR refactor

#4787 [#4781]: Allow passing date range for perform_iati_checks
  akvo/rsr/management/commands/perform_iati_checks.py
  akvo/rsr/management/commands/tests/__init__.py
  akvo/rsr/management/commands/tests/base.py
  akvo/rsr/management/commands/tests/test_perform_iati_checks.py
Labels: Feature request, Chore, Type: IATI

#4776 [ #4774]ci: Pass semaphoreci variables to service
  docker-compose.ci.yaml
Labels: Chore

#4790 [#4582] Fix: input zero at denominator field
  akvo/rsr/spa/app/components/AddUpdate.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results/enumerator.jsx
Labels: Bug

#4791 [#4771] A comma too many, a comma too few
  akvo/rsr/tests/results_framework/test_results_framework.py
  akvo/rsr/views/py_reports/__init__.py
Labels: Chore

#4793 [#4777] make all validation sets available in a clean dev env
  akvo/rsr/fixtures/project_validations.yaml
  akvo/rsr/tests/fixtures/__init__.py
  akvo/rsr/tests/fixtures/test_project_validations.py
  scripts/docker/dev/start-django.sh
Labels: Bug, Chore

#4778 [#4755] Fix: Invalid periods from targetsAt
  akvo/rsr/models/project.py
  akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx
  akvo/rsr/spa/app/modules/editor/section5/section5.jsx
  akvo/rsr/spa/app/utils/required-hint.jsx
Labels: Bug

#4796 Fix [#4795]: Support branch names with a single quote in the CI
  ci/build-semaphoreci.sh
  ci/quote.py
Labels: Bug, Chore

#4797 [#4754] Fix can't delete periods copied from defaults
  akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx
Labels: Bug, Needs Review

#4760 [#4757] Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#4805 [#4803] Fix results overview page
  akvo/rsr/spa/app/components/AuditTrail.jsx
  akvo/rsr/spa/app/components/StatusIndicator.jsx
  akvo/rsr/spa/app/modules/program/indicator.jsx
  akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
  akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.scss
  akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx
  akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx
  akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx
  akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
  akvo/rsr/spa/app/modules/results/styles.scss
  akvo/rsr/spa/app/modules/results/update.jsx
Labels: Bug, Priority: High

#4804 [#4802] Fix: Indicator status panel at Results admin view
  akvo/rsr/spa/app/components/StatusIndicator.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx
  akvo/rsr/spa/app/modules/results-admin/TobeReported.scss
  akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
  akvo/rsr/spa/app/modules/results/styles.scss
Labels: Bug, Priority: High
