Repository akvo/akvo-rsr, pull requests merged in 2023-01, with the labels that each got.

#5190 [#5189] Upgrade jinja2 dependency: MarkupSafe 1.1.1-2.1.1
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/production.in
Labels: Bug

#5203 [#5202]: Deploy master to production by default
  ci/deploy-semaphoreci.sh
  ci/promote-test-to-prod.sh
  doc/deploying.md
Labels: Bug, Chore

#5201 feat: Enhance D2D report with multisheet document output
  akvo/rsr/management/commands/report_d2d.py
Labels: Feature request, Chore

#5207 [#5200] Remove stale bot
  .github/stale.yml
Labels: Chore

#5193 A4a import script failing
  akvo/rsr/management/commands/a4a_optimy_import.py
Labels: Bug

#5151 [#5132] Add tooltip saying 'Please publish first'
  akvo/rsr/spa/app/modules/project-view/project-view.jsx
Labels: Priority: Low, For Production

#5137 Resolve : bug project title changes are reset in frontend when switching view
  akvo/rsr/spa/app/modules/enumerators/enumerators.jsx
  akvo/rsr/spa/app/modules/program/program.jsx
Labels: Bug, Type: Project editor
