Repository akvo/akvo-rsr, pull requests merged in 2023-03, with the labels that each got.

#5204 [#5199] Optimize /project/children endpoint
  akvo/rest/serializers/project.py
  akvo/rest/views/project.py
  akvo/rsr/spa/app/modules/hierarchy/services.js
  akvo/rsr/tests/rest/test_project_hierarchy.py
Labels: Type: Performance

#5240 [#5217] Move A4A optimy import to django-q
  akvo/rsr/management/commands/sync_django_q_schedules.py
  akvo/rsr/tests/usecases/test_schedules.py
  akvo/rsr/usecases/django_q/__init__.py
  akvo/rsr/usecases/django_q/schedules.py
  akvo/settings/90-finish.conf
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/production.in
  scripts/docker/dev/start-django.sh
  scripts/docker/prod/start-django.sh
Labels: Feature request, Chore

#5069 [#5068] Fix see all submissions modal in mobile view
  akvo/rsr/spa/app/components/AllSubmissionsModal.jsx
  akvo/rsr/spa/app/components/UpdatesHistory.jsx
  akvo/rsr/spa/app/images/status-pending.svg
  akvo/rsr/spa/app/images/status-revision.svg
  akvo/rsr/spa/app/modules/results-admin/components/DisaggregationsInput.jsx
  akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.scss
  akvo/rsr/spa/app/modules/results/enumerator.jsx
  akvo/rsr/spa/app/modules/results/enumerator.scss
Labels: Bug, Priority: Medium, Type: Layout/Design

#5244 [#5230] Fix bug standalone project hierarchy
  akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
  akvo/rsr/spa/app/modules/hierarchy/services.js
Labels: Bug

#5245 [#5239] Fix bug cumulative indicator sum up values
  akvo/rsr/spa/app/components/ProgressBar.jsx
  akvo/rsr/spa/app/components/ProgressBar.scss
  akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx
  akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx
  akvo/rsr/spa/app/modules/results/dsg-overview.jsx
  akvo/rsr/spa/app/modules/results/dsg-overview.scss
  akvo/rsr/spa/app/modules/results/period.jsx
Labels: Bug, Priority: Medium

#5250 [#5248] Disable catch-up for django-q
  akvo/settings/41-django-q.conf
Labels: Bug

#5254 [#5249] Add decorator to make django-q tasks unique
  akvo/cache/heartbeat.py
  akvo/rsr/tests/usecases/django_q/__init__.py
  akvo/rsr/tests/usecases/django_q/test_decorators.py
  akvo/rsr/usecases/django_q/decorators.py
  akvo/rsr/usecases/jobs/aggregation.py
  akvo/settings/41-django-q.conf
  akvo/settings/90-finish.conf
Labels: Bug

#5264 [#5263] Provide localhost server for django-q probe
  akvo/rsr/management/commands/django_q_probettp.py
  akvo/rsr/management/commands/probe_django_q.py
  ci/k8s/deployment.yml
  docker-compose.override.yaml
  docker-compose.yaml
  scripts/docker/dev/start-django.sh
  scripts/docker/prod/start-django.sh
  scripts/probes/worker.sh
Labels: Bug

#5266 [#5261] generate reference documentation from docstrings
  .github/workflows/pages.yml
  .gitignore
  Makefile
  akvo/rsr/management/commands/reverse_geocode_city_names.py
  doc/_static/.gitkeep
  doc/_templates/.gitkeep
  doc/conf.py
  doc/dev.md
  doc/index.rst
  gen_doc.py
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/dev.in
Labels: Chore
