Repository akvo/akvo-rsr, pull requests merged in 2023-02, with the labels that each got.

#5215 [#5212] Fix reports period.actual_value for cumulative indicators
  akvo/rest/views/indicator_period_aggregation_job.py
  akvo/rsr/management/commands/recalculate_project_aggregation.py
  akvo/rsr/models/result/disaggregation.py
  akvo/rsr/models/result/indicator_period_data.py
  akvo/rsr/tests/rest/jobs/test_indicator_period_aggregation.py
  akvo/rsr/tests/results_framework/test_cumulative_updates.py
  akvo/rsr/tests/usecases/jobs/test_aggregation.py
  akvo/rsr/usecases/jobs/aggregation.py
Labels: Bug, Priority: High

#5224 [#5211] Fix incorrect aggregated value pg overview
  akvo/rest/views/project_overview.py
  akvo/rsr/spa/app/modules/program/ActualValue.jsx
  akvo/rsr/spa/app/modules/program/indicator.jsx
  akvo/rsr/spa/app/modules/program/result.jsx
  akvo/rsr/spa/app/modules/program/styles.scss
Labels: Bug, Priority: High

#5229 [#5228] Get the actual parent UUID for "contributes to" field
  akvo/rsr/spa/app/modules/editor/section1/section1.jsx
  akvo/rsr/spa/app/utils/misc.js
Labels: Bug, Priority: High, For Production

#5213 [#4680] use a real queue worker
  akvo/rsr/front-end/npm-shrinkwrap.json
  akvo/rsr/management/commands/probe_django_q.py
  akvo/rsr/tests/views/py_reports/test_send_report_via_email.py
  akvo/rsr/views/py_reports/email_report.py
  akvo/rsr/views/py_reports/program_overview_excel_report.py
  akvo/settings/10-base.conf
  akvo/settings/41-django-q.conf
  ci/k8s/deployment.yml
  docker-compose-docker-sync.yaml
  docker-compose.ci.prod.images.yaml
  docker-compose.ci.yaml
  docker-compose.override.yaml
  docker-compose.yaml
  scripts/deployment/pip/requirements/2_rsr.txt
  scripts/deployment/pip/requirements/3_dev.txt
  scripts/deployment/pip/requirements/production.in
  scripts/docker/dev/start-django.sh
  scripts/docker/prod/start-django.sh
Labels: Feature request

#5237 Fix Feature/4680 readiness and liveliness probe for k8s
  ci/k8s/deployment.yml
  scripts/docker/dev/start-django.sh
  scripts/docker/prod/start-django.sh
Labels: Bug, Chore

#5238 [#4680] fix: timings for worker container readiness and liveliness probe
  ci/k8s/deployment.yml
Labels: Bug, Chore
